#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

NAME="uugamebooster"
UU_BIN="/usr/share/uugamebooster/uuplugin"
UU_CONF="/usr/share/uugamebooster/uu.conf"

start_service() {
	local enable
	config_load uuplugin
	config_get_bool enable uuplugin enabled
	if [ "$enable" -eq 1 ]; then
		procd_open_instance
		procd_set_param command $UU_BIN $UU_CONF
		procd_set_param respawn
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "uuplugin"
}
