#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

PROG=/usr/bin/zerotier-one
CONFIG_PATH=/var/lib/zerotier-luci

service_triggers() {
	procd_add_reload_trigger "zerotier"
	procd_add_interface_trigger "interface.*.up" wan /etc/init.d/luci_zerotier restart
}

iptables_w() {
	iptables -w 1 "$@"
}

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}

start_instance() {
	local cfg="$1"
	local port secret config_path
	local ARGS=""

	if ! section_enabled "$cfg"; then
		echo "disabled in config"
		return 1
	fi

	[ -d /etc/config/zero ] || mkdir -p /etc/config/zero
	config_path=/etc/config/zero

	# Remove existing link or folder
	rm -rf $CONFIG_PATH

	# Create link from CONFIG_PATH to config_path
	if [ -n "$config_path" -a "$config_path" != $CONFIG_PATH ]; then
		if [ ! -d "$config_path" ]; then
			echo "ZeroTier config_path does not exist: $config_path"
			return
		fi

		mkdir -p /var/lib
		ln -s $config_path $CONFIG_PATH
	fi

	mkdir -p $CONFIG_PATH/networks.d

	config_get port $cfg 'port'
	[ -f "$CONFIG_PATH/identity.secret" ] || config_get secret $cfg 'secret' "generate"

	if [ -n "$port" ]; then
		ARGS="$ARGS -p$port"
	fi

	if [ "$secret" = "generate" ]; then
		echo "Generate secret - please wait..."
		local sf="/tmp/zt.$cfg.secret"

		zerotier-idtool generate "$sf" > /dev/null
		[ $? -ne 0 ] && return 1

		secret="$(cat $sf)"
		rm "$sf"

		uci set zerotier.$cfg.secret="$secret"
		uci commit zerotier
	fi

	if [ -n "$secret" ]; then
		echo "$secret" > $CONFIG_PATH/identity.secret
		# make sure there is not previous identity.public
		rm -f $CONFIG_PATH/identity.public
	fi

	add_join() {
		# an (empty) config file will cause ZT to join a network
		touch $CONFIG_PATH/networks.d/$1.conf
	}

	rm -f $CONFIG_PATH/networks.d/*.conf
	config_list_foreach $cfg 'join' add_join

	procd_open_instance
	procd_set_param command $PROG $ARGS $CONFIG_PATH
	procd_set_param file /etc/config/zerotier
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	/etc/init.d/zerotier stop 2>/dev/null
	local nat
	config_load 'zerotier'
	config_get_bool nat "sample_config" 'nat' 0
	config_get_bool enabled "sample_config" 'enabled' 0
	if [ "$nat" -eq 1 -a $enabled -eq 1 ]; then
		mkdir -p /var/run/zerotier

		iptables_w -N zerotier_forward
		iptables_w -I FORWARD -i zt+ -j zerotier_forward
		iptables_w -I FORWARD -o zt+ -j zerotier_forward
		iptables_w -t nat -N zerotier_nat
		iptables_w -t nat -I POSTROUTING -j zerotier_nat
	else
		stop_service
	fi
	procd_open_instance zerotier_nat
	procd_set_param command /usr/libexec/zerotier-nat
	procd_close_instance
	config_foreach start_instance 'zerotier'
}

stop_service() {
	rm -rf /var/run/zerotier
	iptables_w -D FORWARD -i zt+ -j zerotier_forward 2>/dev/null
	iptables_w -D FORWARD -o zt+ -j zerotier_forward 2>/dev/null
	iptables_w -t nat -D POSTROUTING -j zerotier_nat 2>/dev/null
	iptables_w -F zerotier_forward 2>/dev/null
	iptables_w -X zerotier_forward 2>/dev/null
	iptables_w -t nat -F zerotier_nat 2>/dev/null
	iptables_w -t nat -X zerotier_nat 2>/dev/null
}
