#!/bin/sh

IPTABLES_FILE=/var/run/zerotier/nat.iptables

iptables_w() {
    echo iptables -w 1 "$@" >>$IPTABLES_FILE
}

while :; do
    [ -d /var/run/zerotier ] || exit 0
    sleep 3
    [ -d /var/run/zerotier ] || exit 0
    [ -f /var/run/zerotier/netchanged ] || continue
    netchanged=$(date '+%s' -r /var/run/zerotier/netchanged)
    now=$(date '+%s')
    [ "$netchanged" -lt "$now" ] || continue
    iptables_before=$(md5sum $IPTABLES_FILE 2>/dev/null || echo "empty" | cut -d ' ' -f 1)
    >$IPTABLES_FILE
    iptables_w -F zerotier_forward
    iptables_w -t nat -F zerotier_nat
    zt0="$(ls /sys/class/net/ | grep -E '^zt[0-9a-z]{8}$' | awk '{print $1}')"
    for i in ${zt0}
    do
        iptables_w -I zerotier_forward -i "$i" -j ACCEPT
        iptables_w -I zerotier_forward -o "$i" -j ACCEPT
        iptables_w -t nat -I zerotier_nat -o "$i" -j MASQUERADE
        ip_segment="$(ip route | grep "dev $i proto kernel" | awk '{print $1}')"
        [ -z "$ip_segment" ] || iptables_w -t nat -I zerotier_nat -s "${ip_segment}" -j MASQUERADE
    done
    iptables_after=$(md5sum $IPTABLES_FILE 2>/dev/null || echo "empty" | cut -d ' ' -f 1)
    [ "$iptables_before" = "$iptables_after" ] && continue
    . $IPTABLES_FILE >/var/run/zerotier/nat.log
done
