
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for cpufreq manage
LUCI_PKGARCH:=all
PKG_VERSION:=1.1
PKG_RELEASE:=3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


