#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@zerotier[-1]
	add ucitrack zerotier
	set ucitrack.@zerotier[-1].init=luci_zerotier
	commit ucitrack
	delete firewall.zerotier
	commit firewall
EOF

/etc/init.d/zerotier disable
sleep 1
if /etc/init.d/zerotier running; then
	echo "stop zerotier" >&2
	/etc/init.d/zerotier stop
	sleep 6
fi

rm -f /tmp/luci-indexcache
exit 0
