#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@zerotier[-1]
	add ucitrack zerotier
	set ucitrack.@zerotier[-1].init=luci_zerotier
	commit ucitrack
	delete firewall.zerotier
	commit firewall
EOF

/etc/init.d/zerotier disable

rm -f /tmp/luci-indexcache
exit 0
